name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Configuração do Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Instalação de dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort pytest pyspark

    # 4. Configurar PYTHONPATH para incluir a raiz do projeto
    - name: Configure PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    # 5. Verificação de formatação com black
    - name: Check code style with black
      run: black --check .

    # 6. Verificação de imports com isort
    - name: Check imports with isort
      run: isort --check-only .

    # 7. Lint com flake8
    - name: Lint with flake8
      run: flake8 .

    # 8. Testes com pytest
    - name: Run tests
      run: pytest tests/
